services:
  # Backend API Service
  - type: web
    name: ai-crop-advisor-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: GEMINI_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: WEATHER_API_KEY
        sync: false  # Set this manually in Render dashboard

  # Frontend Static Site
  - type: web
    name: ai-crop-advisor-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: ai-crop-advisor-backend
          property: host
        value: https://ai-crop-advisor-backend.onrender.com
